# https://taskfile.dev

version: '3'

tasks:
  fmt:
    silent: true
    cmds:
      - pipenv run black .

  lint:
    silent: true
    cmds:
      - pipenv run pylint --rcflie pylintrc src tests

  lint:single:
    silent: true
    cmds:
      - pipenv run pylint --rcflie pylintrc src {{.CLI_ARGS}}

  type:
    silent: true
    cmds:
      - pipenv run pytype src

  update:
    silent: true
    cmds:
      - |
        deps=$(pipenv requirements --exclude-markers | tail -n +2 | awk '{print "\t\""$0"\","}')
        export DEPS=$(printf "$deps")
        envsubst < pyproject.toml.tpl > pyproject.toml

  install:
    silent: true
    cmds:
      - task: update
      - pipenv run python -m pip install -e .

  test:unit:
    cmds:
      - pipenv run pytest tests

  test:unit:single:
    cmds:
      - pipenv run pytest {{.CLI_ARGS}}

  test:cov:
    cmds:
      - pipenv run pytest --cov-report term --cov=src tests

  test:cov:detailed:
    cmds:
      - pipenv run pytest --cov-report term-missing --cov=src tests

  test:e2e:lint:
    cmds:
      - pipenv run bwwl lint --files tests/fixtures

  test:e2e:lint:single:
    cmds:
      - pipenv run bwwl lint --files tests/fixtures/test.yml

  test:e2e:actions:add:
    cmds:
      - pipenv run bwwl actions --output test.json add bitwarden/sm-action

  test:e2e:actions:update:
    cmds:
      - pipenv run bwwl actions --output test.json update

  dist:
    silent: true
    cmds:
      - task: update
      - pipenv run python -m build
