# Workflow templates are based on starter workflows provided by github at
# https://github.com/actions/starter-workflows/tree/main and customized to
# represent common practices used on Bitwarden repositories.

name: CI

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  workflow_call: # Allows this workflow to be called from another workflow
  pull_request: # When a pull request event occurs

permissions: {} # Sets default permissions of the GITHUB_TOKEN

jobs:
  version:
    name: Calculate version
    permissions:
      contents: read # For actions/checkout to fetch code
    uses: ./.github/workflows/examples/example-references/_version.yml # Path to an existing github action

  test:
    name: Run test
    permissions:
      checks: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/examples/example-references/_test.yml
    with: # Parameters specific to this action that need to be defined in order for the step to be completed
      project-name: Billing.Test
      project-path: ./test/Billing.Test

  build:
    name: Run build
    permissions:
      contents: read
    needs: # This job will not run until test and version jobs are complete
      - test
      - version
    uses: ./.github/workflows/examples/example-references/_build.yml
    with:
      project-name: Billing
      project-path: ./src/Billing
      version: ${{ needs.version.outputs.version }}

  build-push-docker:
    name: Build Docker image
    permissions:
      contents: read
      id-token: write
    needs:
      - test
      - version
      - build
    uses: ./.github/workflows/examples/example-references/_docker.yml
    with:
      project-name: Billing
      project-path: ./src/Billing
      version: ${{ needs.version.outputs.version }}
      image-name: billing-relay
      push-docker-image: false
