name: Approved Actions Operations
run-name: ${{ input.operation }} Approved Actions

on:
  workflow_call:
    inputs:
      operation:
        required: true
        types: string
      action:
        required: false
        types: string

jobs:
  actions-update:
    name: "Update Approved Actions"
    runs-on: ubuntu-24.04
    steps:
      - name: Login to Azure - CI Subscription
        uses: Azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
        with:
          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: "bitwarden-ci"
          secrets: "github-gpg-private-key,
            github-gpg-private-key-passphrase"

      - name: Checkout Branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6.2.0
        with:
          gpg_private_key: ${{ steps.retrieve-secrets.outputs.github-gpg-private-key }}
          passphrase: ${{ steps.retrieve-secrets.outputs.github-gpg-private-key-passphrase }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Setup git
        run: |
          git config --local user.email "106330231+bitwarden-devops-bot@users.noreply.github.com"
          git config --local user.name "bitwarden-devops-bot"

      - name: Set up Python 3.11
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.11"

      - name: Install bwwl binary
        run: python -m pip install --upgrade bitwarden_workflow_linter

      - name: Create Branch
        if : inputs.operation == 'update'
        id: create-branch
        run: |
          NAME="update-actions-$(date +'%Y%m%d-%H%M%S')"
          git switch -c $NAME
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: Create Branch
        if : inputs.operation == 'add'
        id: create-branch
        env:
          _ACTION: ${{ inputs.action }}
        run: |
          NAME= "add-action-$_ACTION"
          git switch -c $NAME
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: Run bwwl update
        if: inputs.operation == 'update'
        run: bwwl actions update -o src/bitwarden_workflow_linter/default_actions.json

      - name: Run bwwl update
        if: inputs.operation == 'add'
        run: bwwl actions add -o src/bitwarden_workflow_linter/default_actions.json ${{ inputs.action }}

      - name: Commit changes
        env:
          _PR_BRANCH: ${{ steps.create-branch.outputs.name }}
          _OP: ${{ inputs.operation }}
        run: |
          git commit -m "${{ env._OP }} approved actions" -a
          git push origin $_PR_BRANCH

      - name: Generate GH App token
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Create PR
        id: create-pr
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          _PR_BRANCH: ${{ steps.create-branch.outputs.name }}
          _TITLE: "bwwl Update/Add Approved Actions"
          _OP: ${{ inputs.operation }}
        run: |
          PR_URL=$(gh pr create --title "$_TITLE" \
            --base "main" \
            --head "$_PR_BRANCH" \
            --label "version:patch" \
            --label "automated pr" \
            --body "
              ## Type of change
              - [ ] Bug fix
              - [ ] New feature development
              - [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
              - [ ] Build/deploy pipeline (DevOps)
              - [ ] Other

              ## Description
              - This PR ${{ env._OP }}s to the approved actions for the Bitwarden Workflow Linter.")
          echo "pr_number=${PR_URL##*/}" >> $GITHUB_OUTPUT

      - name: Approve and Merge PR
        if: ${{ steps.create-pr.outcome == 'success' }}
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          _PR_NUMBER: ${{ steps.create-pr.outputs.pr_number }}
        run: |
          gh pr review $_PR_NUMBER --approve
          gh pr merge $_PR_NUMBER --squash --auto --delete-branch
