name: _version_type
run-name: Get version type

on:
  workflow_call:
    outputs:
      version_bump_type:
        description: "version to be built"
        value: ${{ jobs.version.outputs.bump_type }}

jobs:
  version:
    name: Calculate Version
    runs-on: ubuntu-22.04
    outputs:
      bump_type: ${{ steps.bump-type.outputs.type }}
    steps:
      - name: Get PR ID
        id: pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          commit_message=$(
            curl -s -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }} | \
            jq -r ".commit.message"
          )
          ID=$(echo "$commit_message" | head -1 | grep -o "(#.*)" | grep -o "[0-9]*")
          echo "id=$ID" >> $GITHUB_OUTPUT

      - name: Get version bump type
        id: bump-type
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.pr.outputs.id }}
        run: |
          version_tag=$(
            curl -s -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels | \
            jq -r ".[].name" | grep "version"
          )

          # Single Version label Enforcement (should go in CI...)
          if [[ $(echo $version_tag | wc -w) -gt 1 ]]; then
              echo "[!] multiple version labels found!"
              exit 1
          fi

          version_type=$(echo $version_tag | cut -d ":" -f 2)
          echo "Version Bump Type: $version_type"
          echo "type=$version_type" >> $GITHUB_OUTPUT
