name: Test Actionlint on Windows

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/run_actionlint.py"
      - "**/default_actions.json"

jobs:
  test:
    name: Windows workflow-linter (v2)
    runs-on: windows-2022
    steps:
        - name: Check out repo
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
  
        - name: Set up Python
          uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
          with:
            python-version-file: ".python-version"

        # - name: Check Actionlint
        #   run: |
        #     actionlint --version

        # - name: Install actionlint
        #   run: |
        #     choco install actionlint -y -v --version=1.6.17
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
        #     pip install pipenv
        #     pipenv install --dev

        - name: Lint
          uses: uses: bitwarden/gh-actions/test-lint-workflow@6e3f7024df22b3d91c19c053133a25c389e88b8d
