name: Test Actionlint on Windows

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/run_actionlint.py"
      - "**/default_actions.json"

jobs:
  test:
    name: CI workflow-linter (v2)
    runs-on: windows-2022
    steps:
        - name: Check out repo
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
  
        - name: Set up Python
          uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
          with:
            python-version-file: ".python-version"
  
        - name: Install pip
          run: |
            python -m pip install --upgrade pip
    
        - name: Install pipenv
          run: |
            pip install pipenv
            
        - name: Install dev
          run: |
            pipenv install --dev
      
        - name: Run pytest
          run: pipenv run pytest tests --cov=src
  
        - name: Check type hinting
          run: pipenv run pytype src
  