name: Test Actionlint on Windows

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/run_actionlint.py"
      - "**/default_actions.json"

jobs:
  test:
    name: Windows workflow-linter (v2)
    runs-on: windows-2022
    steps:
        - name: Check out repo
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
  
        - name: Set up Python
          uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
          with:
            python-version-file: ".python-version"
  
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pipenv
            pipenv install --windows

            - name: Enable WSL and Install Ubuntu
            shell: pwsh
            run: |
              # Enable WSL feature on Windows
              dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
              dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
              wsl --set-default-version 2  # Set WSL 2 as the default version
    
              # Download and install Ubuntu from Microsoft Store (using PowerShell)
              Invoke-WebRequest -Uri https://aka.ms/wsl-ubuntu-2004 -OutFile ubuntu-2004.appx -UseBasicP -SkipHttpValidation
              Add-AppxPackage .\ubuntu-2004.appx
    
              # Install Ubuntu if not already installed (you can specify other distributions)
              wsl --install --distribution Ubuntu-24.04  # Replace with your preferred Linux distribution
    
        - name: Run pytest
          run: pipenv run pytest tests --cov=src
  
        - name: Check type hinting
          run: pipenv run pytype src
  