name: Test Actionlint on Windows

on:
  push:
    branches:
      - "agalles/renovate-actionlint"
  pull_request:
    branches:
      - main
    # paths:
    #   - "**/run_actionlint.py"
    #   - "**/default_actions.json"

jobs:
  test:
    name: Windows workflow-linter (v2)
    runs-on: windows-2022
    steps:
        - name: Check out repo
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
  
        - name: Set up Python
          uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
          with:
            python-version-file: ".python-version"

        # - name: Check Actionlint
        #   run: |
        #     actionlint --version

        # - name: Install actionlint
        #   run: |
        #     choco install actionlint -y -v --version=1.6.17
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
        #     pip install pipenv
        #     pipenv install --dev

        - name: Get workflow list
          id: workflow-list
          run: |
            WORKFLOW_LIST=$(ls .github/workflows | xargs -I {} echo -n ".github/workflows/{} ")
            echo "workflow-list=$WORKFLOW_LIST" >> $GITHUB_OUTPUT

        - name: Lint Workflow
          uses: bitwarden/gh-actions/.github/workflows/lint-workflow@main
          with:
            workflows: ${{ steps.workflow-list.outputs.workflow-list }}
