name: Test Actionlint on Windows

on:
  push:
    branches:
      - "agalles/renovate-actionlint"
  pull_request:
    branches:
      - main
    # paths:
    #   - "**/run_actionlint.py"
    #   - "**/default_actions.json"

jobs:
  test:
    name: Windows workflow-linter (v2)
    runs-on: windows-2022
    steps:
        - name: Check out repo
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
  
        - name: Set up Python
          uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
          with:
            python-version-file: ".python-version"

        # - name: Check Actionlint
        #   run: |
        #     actionlint --version

        # - name: Install actionlint
        #   run: |
        #     choco install actionlint -y -v --version=1.6.17
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install --user yamllint
        
        - name: Get workflow list
          id: workflow-list
          run: |
            WORKFLOW_LIST=$(ls .github/workflows | xargs -I {} echo -n ".github/workflows/{} ")
            echo "workflow-list=$WORKFLOW_LIST" >> $GITHUB_OUTPUT
        #     pip install pipenv
        #     pipenv install --dev

        # - name: Get workflow list
        #   id: workflow-list
        #   run: |
        #     WORKFLOW_LIST=$(ls .github/workflows | xargs -I {} echo -n ".github/workflows/{} ")
        #     echo "workflow-list=$WORKFLOW_LIST" >> $GITHUB_OUTPUT

        # - name: Lint Workflow
        #   uses: bitwarden/gh-actions/.github/workflows/lint-workflow@main
        #   with:
        #     workflows: ${{ steps.workflow-list.outputs.workflow-list }}
        - name: Setup
          id: setup 
          run: |
            FORMAT_PATH=$(echo ${{ steps.workflow-list.outputs.workflow-list }} | sed 's/ *$//')
            echo "path=$FORMAT_PATH" >> $GITHUB_OUTPUT
          shell: bash
          
        # - name: Install bwwl binary
        #   run: python -m pip install --upgrade bitwarden_workflow_linter

        # - name: Lint
        #   run: bwwl lint -f .github/workflows

        - name: Python lint
          run: python ../src/bitwarden_workflow_linter/lint.py "${{ steps.setup.outputs.path }}"
          shell: bash

        - name: YAML lint
          run: |
            WORKFLOWS=($(echo "${{ steps.setup.outputs.path }}" | tr ' ' '\n'))
            for WORKFLOW in "${WORKFLOWS[@]}"; do
              yamllint -f colored -c ${{ github.action_path }}/.yamllint.yml $WORKFLOW
            done
          shell: bash
          working-directory: ${{ github.workspace }}

