name: CD
run-name: ${{ inputs.test == true && 'CD - Test' || 'CD' }}

on:
  pull_request:
    types:
      - closed
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      test:
        description: "Publish to Test PyPI for testing (Does not create a release)"
        required: false
        default: false
        type: boolean

permissions: {}

jobs:
  deploy:
    name: Trigger publish via deploy repo
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Trigger publish
        uses: bitwarden/gh-actions/trigger-actions@main
        with:
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          task: publish-workflow-linter
