name: Lint Example Workflows

on:
    pull_request:
      branches:
        - "main"
    merge_group:
      types: [checks_requested]
    workflow_call:
    workflow_dispatch:  

jobs:
    test-lint-workflow:
        name: Test Lint Workflow
        runs-on: ubuntu-24.04
        steps:
          - name: Checkout Branch
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

          - name: Get workflow list
            id: workflow-list
            run: |
                WORKFLOW_LIST=$(find .github/workflows/examples -maxdepth 1 -type f | xargs -I {} echo -n "{} ")
                echo "workflow-list=$WORKFLOW_LIST" >> $GITHUB_OUTPUT

          - name: Lint examples
            id: lint-examples
            uses: bitwarden/gh-actions/lint-workflow@main
            with:
                workflows: ${{ steps.workflow-list.outputs.workflow-list }}

          - name: Failure message
            if: ${{ failure() && steps.lint-examples.conclusion == 'failure' }}
            run: echo "And NOW this step will run"
  
