name: Lint Example Workflows

on:
    pull_request:
      paths:
        - .github/workflows/**
    merge_group:
      types: [checks_requested]
    workflow_call:
    workflow_dispatch:  

jobs:
    test-lint-workflow:
        name: Test Lint Workflow
        runs-on: ubuntu-24.04
        steps:
          - name: Checkout Branch
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

          - name: Get workflow list
            id: workflow-list
            run: |
                WORKFLOW_LIST=$(ls .github/workflows/examples | xargs -I {} echo -n ".github/workflows/examples/{} ")
                echo "workflow-list=$WORKFLOW_LIST" >> $GITHUB_OUTPUT

          - name: Lint examples
            uses: bitwarden/gh-actions/lint-workflow@main
            with:
                workflows: ${{ steps.workflow-list.outputs.workflow-list }}
        