name: Test approved actions operations

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-actions-operation:
    name: "Test approved actions operations"
    runs-on: ubuntu-24.04
    env:
      _ACTION: someowner/somerepo@1234567890abcdef123456789012345678901234 # A fake action reference for testing
    steps:

      - name: Checkout Branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python 3.12
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"

      - name: Install bwwl binary
        run: python -m pip install --upgrade bitwarden_workflow_linter

      - name: Run bwwl update
        run: bwwl actions update -o src/bitwarden_workflow_linter/default_actions.json

      - name: Run bwwl add
        run: bwwl actions add -o src/bitwarden_workflow_linter/default_actions.json "$_ACTION"
