name: Update Approved Actions

on:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  actions-update:
    name: "Update Approved Actions"
    uses: ./.github/workflows/_bwwl_operations.yml
    with:
      operation: 'update'
