name: Lint workflow

on:
  pull_request:
    paths:
      - .github/workflows/**
  merge_group:
    types: [checks_requested]
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Get repository
        id: repo
        env:
          REPO: ${{ github.repository }}
        run: |
          echo $REPO
          echo "repo=$REPO" >> $GITHUB_OUTPUT

      - name: Check out branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{ steps.repo.outputs.repo }}
          fetch-depth: 0

      - name: Get changed files
        id: changed-workflows
        uses: tj-actions/changed-files@c3a1bb2c992d77180ae65be6ae6c166cf40f857c # v45.0.3
        with:
          files: .github/workflows/**

      - name: Set up Python 3.11
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.11"

      - name: Install bwwl binary
        if: steps.changed-workflows.outputs.all_changed_files_count != 0
        run: python -m pip install --upgrade bitwarden_workflow_linter

      - name: Lint
        if: steps.changed-workflows.outputs.all_changed_files_count != 0
        run: bwwl lint -f .github/workflows
  test-report-start:
    name: Test Slack report
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Start
        uses: bitwarden/gh-actions/report-deployment-status-to-slack/action.yml@main
        with:
          project: $TEST_REPORT_PROJECT
          environment: EU-QA Cloud
          slack-channel: bre-alerts-test
          tag: test-workflow-start
          event: 'start'
          commit-sha: $TEST_REPORT_COMMIT_SHA
          url: https://github.com/bitwarden/gh-actions/actions/runs/${{ github.run_id }}
          AZURE_KV_CI_SERVICE_PRINCIPAL: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: Success
        uses: bitwarden/gh-actions/report-deployment-status-to-slack/action.yml@main
        with:
          project: $TEST_REPORT_PROJECT
          environment: US-QA Cloud
          slack-channel: bre-alerts-test
          tag: test-workflow-success
          event: 'success'
          commit-sha: $TEST_REPORT_COMMIT_SHA
          url: https://github.com/bitwarden/gh-actions/actions/runs/${{ github.run_id }}
          AZURE_KV_CI_SERVICE_PRINCIPAL: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: Failure
        uses: bitwarden/gh-actions/report-deployment-status-to-slack/action.yml@main
        with:
          project: $TEST_REPORT_PROJECT
          environment: US-QA Cloud
          slack-channel: bre-alerts-test
          tag: test-workflow-failure
          event: 'failure'
          commit-sha: $TEST_REPORT_COMMIT_SHA
          url: https://github.com/bitwarden/gh-actions/actions/runs/${{ github.run_id }}
          AZURE_KV_CI_SERVICE_PRINCIPAL: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}

      - name: No Changes
        uses: bitwarden/gh-actions/report-deployment-status-to-slack/action.yml@main
        with:
          project: $TEST_REPORT_PROJECT
          environment: EU-QA Cloud
          slack-channel: bre-alerts-test
          tag: test-workflow-failure
          event: 'no-changes'
          commit-sha: $TEST_REPORT_COMMIT_SHA
          url: https://github.com/bitwarden/gh-actions/actions/runs/${{ github.run_id }}
          AZURE_KV_CI_SERVICE_PRINCIPAL: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
